<template>
  <input
  id="inline-full-name"
  class="
    bg-primary
    appearance-none
    border-2
    border-gray-200
    rounded
    w-full
    py-2
    px-4
    text-gray-700
    leading-tight
    focus:outline-none
    focus:bg-gray-800
    text-secondary
    focus:border-purple-500"
   type="text" value="Merlion">
</template>
